<?xml version="1.0" encoding="utf-8"?> <!DOCTYPE beans [
        <!ELEMENT beans (bean)*>
        <!ELEMENT bean (property)*>
        <!ATTLIST bean
                id CDATA #REQUIRED
                class CDATA #REQUIRED
                >
        <!ELEMENT property (#PCDATA)>
        <!ATTLIST property
                name CDATA #REQUIRED
                ref CDATA #REQUIRED>
        ]>
<beans>

    <bean id="page" class="com.atguigu.myssm.myspringmvc.PageController"/>

    <!-- DAO -->
    <bean id="userDAO" class="com.atguigu.book.dao.impl.UserDAOImpl"/>
    <bean id="bookDAO" class="com.atguigu.book.dao.impl.BookDAOImpl" />
    <bean id="cartItemDAO" class="com.atguigu.book.dao.impl.CartItemDAOImpl" />
    <bean id="orderDAO" class="com.atguigu.book.dao.impl.OderDAOImpl" />
    <bean id="orderItemDAO" class="com.atguigu.book.dao.impl.OderItemDAOImpl" />


    <!-- Service -->
    <bean id="userService" class="com.atguigu.book.service.impl.UserServiceImpl">
        <property name="userDAO" ref="userDAO" />
    </bean>
    <bean id="bookService" class="com.atguigu.book.service.impl.BookServiceImpl">
        <property name="bookDAO" ref="bookDAO" />
    </bean>
    <bean id="cartItemService" class="com.atguigu.book.service.impl.CartItemServiceImpl">
        <property name="cartItemDAO" ref="cartItemDAO" />
        <property name="bookService" ref="bookService" />
    </bean>
    <bean id="orderService" class="com.atguigu.book.service.impl.OrderServiceImpl">
        <property name="orderDAO" ref="orderDAO" />
        <property name="orderItemDAO" ref="orderItemDAO" />
        <property name="cartItemDAO" ref="cartItemDAO" />
    </bean>


    <!-- Controller -->
    <bean id="user" class="com.atguigu.book.controller.UserController">
        <property name="userService" ref="userService" />
        <property name="cartItemService" ref="cartItemService"/>
    </bean>
    <bean id="book" class="com.atguigu.book.controller.BookController">
        <property name="bookService" ref="bookService" />
    </bean>
    <bean id="cart" class="com.atguigu.book.controller.CartController">
        <property name="cartItemService" ref="cartItemService" />
    </bean>
    <bean id="order" class="com.atguigu.book.controller.OrderController">
        <property name="orderService" ref="orderService" />
    </bean>



</beans>
