<?xml version="1.0" encoding="utf-8"?> <!DOCTYPE beans [
        <!ELEMENT beans (bean)*>
        <!ELEMENT bean (property)*>
        <!ATTLIST bean
                class CDATA #REQUIRED
                id CDATA #REQUIRED>
        <!ELEMENT property (#PCDATA)>
        <!ATTLIST property
                name CDATA #REQUIRED
                ref CDATA #REQUIRED>
        ]>
<beans>
    <bean id="user" class="com.atguigu.qqzone.controller.UserController">
        <property name="userBasicService" ref="userBasicService"/>
        <property name="topicService" ref="topicService"/>
    </bean>
    <bean id="topic" class="com.atguigu.qqzone.controller.TopicController">
        <property name="topicService" ref="topicService"/>
    </bean>
    <bean id="reply" class="com.atguigu.qqzone.controller.ReplyController">
        <property name="replyService" ref="replyService"/>
    </bean>
    <bean id="page" class="com.atguigu.myssm.myspringmvc.PageController"/>


    <bean id="userBasicService" class="com.atguigu.qqzone.service.imp.UserBasicServiceImp">
        <property name="userBasicDAO" ref="userBasicDAO"/>
    </bean>
    <bean id="topicService" class="com.atguigu.qqzone.service.imp.TopicServiceImp">
        <property name="topicDAO" ref="topicDAO"/>
        <property name="replyService" ref="replyService"/>
        <property name="userBasicService" ref="userBasicService"/>
    </bean>
    <bean id="replyService" class="com.atguigu.qqzone.service.imp.ReplyServiceImp">
        <property name="replyDAO" ref="replyDAO"/>
        <property name="hostReplyService" ref="hostReplyService"/>
        <property name="userBasicService" ref="userBasicService"/>
    </bean>
    <bean id="hostReplyService" class="com.atguigu.qqzone.service.imp.HostReplyServiceImp">
        <property name="hostReplyDAO" ref="hostReplyDAO"/>
    </bean>


    <bean id="userBasicDAO" class="com.atguigu.qqzone.dao.img.UserBasicDAOImp"/>
    <bean id="topicDAO" class="com.atguigu.qqzone.dao.img.TopicDAOImp"/>
    <bean id="replyDAO" class="com.atguigu.qqzone.dao.img.ReplyDAOImp"/>
    <bean id="hostReplyDAO" class="com.atguigu.qqzone.dao.img.HostReplyDAOImp"/>

</beans>
